import React from 'react'
import './About.css'
import image1 from './images/Ship.jpg'
import Navbar from './Nav/Navbar'

function About() {
  return (
    <div>
      <Navbar/>
      <h1 className='heading-about1'>About E-kart</h1>
      <p>
        Welcome to our website! We are a team of passionate individuals dedicated to providing
        high-quality products/services to our customers.
      </p>
      <p>
        Our mission is to provide better quality products. Lorem ipsum dolor sit
        amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua.
      </p>
      <p>
        Feel free to explore our website and discover the amazing products/services we have to
        offer.
      </p>
      <p>
        To know more about <a href='https://en.wikipedia.org/wiki/Talk:Ekart'>Click here.... </a>
        And we have lisence Registeration, To know about our lisence click this
        <a href='https://en.wikipedia.org/wiki/Private_company_limited_by_shares'>
          link
        </a>
      </p>
      <h1 className='heading-about2'>Our Shipping style</h1><br/>
      <img src={image1} alt='Ship' className='About-img1' /> <p>          </p><p>Freight containers are a reusable transport 
        and storage unit for moving products and raw materials between locations or countries. 
        There are about seventeen million intermodal containers in the world, and a large proportion .
        of the world's long-distance freight generated by international trade is transported 
        in shipping containers. In addition, it is estimated that several million of these 
        containers have now been discarded due to the shipping cost of sending them back to 
        their port of origin. Their invention made a major contribution to the globalization of 
        commerce in the second half of the 20th century, dramatically reducing the cost of 
        transporting goods and hence of long-distance trade</p><br/>
        <h2 className='heading-about3'>Anything else...</h2>
        <p>Contact us or Click here to know our benificial Policy .<a href='https://en.wikipedia.org/wiki/Shipping_container'>
           Just Click</a></p><br/><br/><br/><br/><br/><br/>
    </div>
  )
}

export default About
